import type { Metadata } from "next";
import { Providers } from './providers';
import { Box } from "@chakra-ui/react";
import { fonts } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang='en' className={fonts.lato.variable}>
      <body>
        <Providers>
          <Box minH="100vh" bg="red">
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  )
}